attack-site-noun-420 = Napadalna stran!
authenticate-verb-418 = Brez overjanja, če je geslo shranjeno
authenticated-adjective-417 = Opozorilo: vsebuje neoverjeno vsebino
autoplay-noun-416 = Za to stran ste zavrnili samodejno predvajanje večpredstavnosti z zvokom.
bookmark-verb-414 = Dodaj stran med zaznamke
certificate-authority-noun-413 = Potrdilo, ki se ga je uporabilo za podpis sporočila, je izdal neznan overitelj potrdil.
clipboard-noun-411 = Kopiraj besedilo v odložišče
contribute-verb-407 = Sodelujte pri razvoju dodatkov
corrupt-adjective-406 = Tega dodatka ni bilo mogoče namestiti, ker je verjetno poškodovan.
counterclockwise-adverb-403 = Zavrti v nasprotni smeri urnega kazalca
cryptominer-noun-402 = Kriptorudarji izrabljajo zmogljivost vašega računalnika za rudarjenje digitalnega denarja. Rudarski skripti vam praznijo baterijo, upočasnjujejo računalnik in zasolijo račun za elektriko.
cypher-noun-400 = Šifra, ki se uporablja za šifriranje, je zastarela in nevarna.
decentralization-noun-302 = Decentralizacija pomeni nepristranskost spleta
decryption-noun-390 = Modul Widevine Content Decryption podjetja Google Inc.
digital-citizenship-noun-298 = Kako lahko negujete svoje digitalno državljanstvo
encrypt-verb-392 = Šifriraj to sporočilo
encryption-noun-391 = Vaša povezava na to stran uporablja šibko šifriranje in ni zasebna.
fake-news-noun-289 = Naučite se prepoznati lažne novice
fingerprinter-noun-385 = Sledilci prstnih odtisov zbirajo nastavitve vašega brskalnika in računalnika, da si ustvarijo vaš profil. S pomočjo digitalnega prstnega odtisa vam lahko sledijo po različnih spletnih mestih.
gear-noun-283 = Uradna Mozillina oprema je tukaj
home-page-noun-383 = Želite to stran nastaviti kot domačo stran?
independent-browser-noun-275 = Izberite neodvisen brskalnik
interactive-adjective-272 = Naučite se izkoristiti interaktivno moč spleta
pop-up-noun-373 = Za to stran ste zavrnili pojavna okna.
remix-verb-246 = Naučite se ustvarjanja novih vsebin z mešanjem obstoječih
report-noun-371 = Pošljite poročilo o sesutju za prikazan zavihek
report-verb-370 = S prijavo podobnih napak pomagate Mozilli prepoznati in zavračati zlonamerne strani
security-keys-noun-367 = %S želi registrirati račun z enim izmed vaših varnostnih ključev. Lahko ga povežete in pooblastite zdaj ali prekličete.
sidebar-noun-364 = Naloži ta zaznamek v stransko vrstico
student-ambassador-noun-236 = Pridružite se nam kot študentski zastopnik
track-verb-360 = Zavračajte vsebino tretjih strani, ki vam sledi po spletu. Nadzirajte, koliko vaše spletne dejavnosti se shranjuje in deli med spletnimi stranmi.
tracking-content-noun-359 = Spletne strani lahko naložijo zunanje oglase, videoposnetke in drugo vsebino, ki vsebuje kodo za sledenje. Zavračanje sledilne vsebine lahko pospeši nalaganje spletnih strani, vendar nekateri gumbi in obrazci morda ne bodo delovali.
validate-verb-352 = Preveri manifest predpomnilnika
validity-noun-353 = Uporabi strežnike OCSP za potrditev trenutne veljavnosti digitalnih potrdil
web-authentication--350 = Odpri ploščo za spletno overitev
