abnormality-noun-345 = Mozilla detected a serious abnormality in its internal data
abort-verb-426 = Do you want to abort this download
abuse-verb-330 = In addition any participants who abuse the reporting process will be considered to be in violation of these guidelines
abuse-noun-331 = Special thanks to all of you who help report abuses of Mozilla marks
accessible-adjective-329 = The Web should remain open and accessible to all
accountability-noun-328 = Transparent community based processes promote participation accountability and trust
accountable-adjective-327 = Governments should be held accountable
activist-noun-326 = We connect support and amplify the work of technologists policy wonks artists and activists committed to helping shape and drive Mozilla’s campaigns
add-on-noun-425 = Your add-ons and customizations have been removed and your browser settings have been restored to their defaults.
adoption-noun-324 = We are committed to driving forward the adoption of HTML as a platform for the mobile industry
ad-targeting-noun-325 = Ad targeting: Who’s behind it?
advertising-networks-noun-323 = Firefox will tell advertising networks and other websites and applications that you want to opt out of tracking
advocacy-noun-322 = The foundation that supports and drives our advocacy work by bringing together awesome people
aggregate-noun-349 = We encourage users to visualize the state of tracking as an aggregate
aggregate-adjective-348 = Generating aggregate reports
alternate-text-noun-424 = If the image is relevant to the content of the document, you must supply alternate text that will appear in text-only browsers
appear-verb-422 = Choose the alternative search engines that appear below the address bar; The add-on downloaded from this site could not be installed because it appears to be corrupt.
appearance-noun-423 = Modify the appearance and importance of tags using the settings below
artist-noun-321 = Developers designers and artists are able to easily create accessible VR experiences
attack-verb-419 = This site is likely to attack your browser.
attacker-noun-421 = An attacker could easily reveal information which you thought to be safe
attack-site-noun-420 = Reported Attack Site!
attendee-noun-344 = This option sends one invitation email per attendee
authenticate-verb-418 = Do not prompt for authentication if password is saved
authenticated-adjective-417 = Warning: Contains unauthenticated content
autoplay-noun-416 = You have blocked autoplay media with sound for this website.
behavioral-advertising-noun-320 = Firefox will tell advertising networks and other websites and applications that you want to optout of tracking for purposes like behavioral advertising
black-box-verb-347 = The following sources were black boxed
bookmark-verb-414 = Bookmark this page
bookmark-noun-415 = Bookmarks you add will still be saved on your device.
boolean-adjective-343 = Toggles the boolean preference specified by input
boot-verb-342 = You have been booted from the chatroom
breakpoint-noun-346 = Resumes the main thread and continues execution following a breakpoint until the next breakpoint or the termination of the script
browsing-habits-noun-319 = Collect information about our browsing habits
bug-noun-318 = Firefox engineers livehack and crush bugs
builders-noun-317 = At Mozilla we’re a global community of technologists thinkers and builders
buyers-guide-noun-316 = Following up on our super-popular “Privacy Not Included” holiday buyer’s guide, we’re expanding our list of products under review and planning a deep-dive into one or two specific product categories.
certificate-authority-noun-413 = The certificate used to sign the message was issued by an unknown certificate authority.
channel-noun-412 = You are currently on the Firefox release channel
clipboard-noun-411 = Copy text to clipboard
clockwise-adverb-410 = Rotate clockwise
compact-adjective-409 = Choose a compact theme to make more room for tabbed browsing
compact-recommend-deprioritize-verb-341 = Do you wish to compact all local and offline folders to save disk space?
compact-view-noun-340 = Favorite Folders Compact View
confidentiality-noun-315 = Respect people’s right to privacy and confidentiality
context-noun-338 = A Geolocation request can only be fulfilled in a secure context. This scratchpad executes in the Browser context.
contribute-verb-407 = Contribute to the development of this add-on
contribute-verb-408 = Contribute {n} dollars to the cause.
copyright-reform-noun-314 = Advocating for net neutrality copyright reform and other issues
corrupt-adjective-406 = This add-on could not be installed because it appears to be corrupt.
corrupt-verb-405 = The response from the OCSP server was corrupted or improperly formed
corrupted-adjective-404 = Invalid or corrupted PDF file
counterclockwise-adverb-403 = Rotate Counterclockwise
crash-noun-313 = Install Nightly and help us improve Firefox quality hunt crashes and regressions
creators-noun-312 = Calling the creators of today’s Internet
cross-site-tracking-cookies-noun-358 = These cookies follow you from site to site to gather data about what you do online. They are set by third parties such as advertisers and analytics companies. Blocking cross-site tracking cookies reduces the number of ads that follow you around.
crowdsourced-adjective-311 = Mozilla Stumbler is an opensource wireless network scanner which collects GPS cellular and wireless network metadata for our crowdsourced location database
cryptominer-noun-402 = Cryptominers use your system’s computing power to mine digital money. Cryptomining scripts drain your battery, slow down your computer, and can increase your energy bill.
curriculum-noun-310 = Creating open curricula that empowers people
customizable-adjective-309 = Firefox Marketplace will offer developers’ discovery distribution and monetization opportunities and will also be customizable by partners
cyberattack-noun-305 = At this point it feels like we’ve all been victims of a cyberattack
cyberbullying-noun-304 = iscouraging people from getting online cyberbullying and cyber violence threaten not just individuals but the Internet itself
cyber-bullying-noun-308 = iscouraging people from getting online cyberbullying and cyber violence threaten not just individuals but the Internet itself
cybersecurity-noun-303 = cybersecurity is actually really simple it just means protecting yourself and your information online
cyber-security-noun-307 = cybersecurity is actually really simple it just means protecting yourself and your information online
cyber-violence-noun-306 = iscouraging people from getting online cyberbullying and cyber violence threaten not just individuals but the Internet itself
cypher-noun-400 = The cipher used for encryption is deprecated and insecure.
debug-verb-399 = Turning this on will allow you to debug Add-ons
decentralization-noun-302 = Decentralization means Net Neutrality
deceptive-site-noun-398 = This web page has been reported as a deceptive site and has been blocked
decode-verb-393 = Media resource could not be decoded
decryption-noun-390 = Widevine Content Decryption Module provided by Google Inc.
designer-noun-301 = Designers and artists are able to easily create accessible VR experiences
developer-noun-300 = Developers are able to easily create accessible VR experiences
digital-citizen-noun-299 = Together these informed digital citizens move beyond just consuming content
digital-citizenship-noun-298 = How you can cultivate your digital citizenship
digital-footprint-noun-297 = But our digital footprints reveal more about us than where we’ve been
digital-lockbox-noun-296 = If you had a digital lockbox that no one could see but you what would you put in it
disinformation-noun-295 = Political actors use disinformation campaigns that prey on our emotions and values to manipulate our behaviour.
distrust-verb-397 = If you delete or distrust a certificate authority (CA) certificate, this application will no longer trust any certificates issued by that CA
doxxing-noun-294 = This also includes posting or threatening to post other people’s personally identifying information doxxing online
early-adopter-noun-293 = Nightly is updated daily It is most appropriate for core Mozilla contributors and early adopters not regular users
eavesdropping-verb-339 = Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.
emoji-noun-292 = emojis like kiss
enable-verb-396 = You cannot enable this filter
encode-verb-395 = Check that the file, including symbols and accented letters, is encoded using the UTF-8 character encoding.
encrypt-verb-392 = Encrypt This Message
encryption-noun-391 = Your connection to this website uses weak encryption and is not private.
end-user-noun-389 = Request on the main thread is deprecated because of its detrimental effects to the end user
engine-noun-291 = The layout engine that drives Firefox
evangelist-noun-290 = A passionate open source evangelist
executable-file-noun-388 = Executable files may contain viruses or other malicious code
extension-noun-387 = This page is loaded from an extension
external-adjective-386 = an external application must be launched to handle javascript
fake-news-noun-289 = Learn to spot fake news
fellow-noun-288 = Mozilla Fellows are working to stop the spread of misinformation, put individuals in control of their data, keep artificial intelligence accountable, and provide innovative solutions for internet connectivity in low penetration environments.
filter-bubble-noun-287 = Fake news and filter bubbles are making it harder for us to find our way.
fingerprinter-noun-385 = Fingerprinters collect settings from your browser and computer to create a profile of you. Using this digital fingerprint, they can track you across different websites.
forum-noun-286 = Special thanks to all of you who help report abuses of Mozilla marks participate in governance forums
gaming-noun-285 = Firefox is leading the charge in online gaming
gatekeepers-noun-284 = We will take on new threats to the Web’s future from locked down proprietary platforms to wouldbe censors and gatekeepers
gear-noun-283 = Official Mozilla gear is here
gif-noun-282 = Create your own Web content like videos blog posts GIF
global-community-noun-281 = The real power behind Mozilla is a global community of of volunteers
glossary-noun-280 = Visit our cybersecurity glossary on Shape of the Web
government-surveillance-noun-279 = Mozilla’s policy team proposes that government surveillance must follow three fundamental principles
grassroots-adjective-278 = Use market-leading research to deliver powerful grassroots-led campaigns.
guidelines-noun-277 = These guidelines aim to support a community where all people should feel safe
home-page-noun-383 = Do you want this document to be your new home page?
identity-noun-276 = Which means your identity may be at risk of theft without you even knowing it
idle-adjective-382 = The worker was idle for a relatively long time
import-verb-381 = Select which items to import
independent-browser-noun-275 = Choose the independent browser
innovations-noun-274 = Explore some of our latest innovations
innovator-noun-273 = All of which creates obstacles and uncertainty for innovators and leaves the door open for patent trolls
insecure-adjective-380 = Firefox has detected an insecure site. Form Autofill is temporarily disabled.
installation-noun-379 = A restart of your computer may be required to complete the installation. -or- This setting will apply to all Windows accounts and Firefox profiles using this installation of Firefox.
interactive-adjective-272 = Learn how to maximize the interactive potential of the Web
internet-health-noun-271 = Mozilla believes diverse initiatives impacting the world power a healthy internet.
interoperable-adjective-270 = The Web should remain open and interoperable
issue-verb-377 = The certificate used to sign the message was issued by a certificate authority whose own certificate has expired.
issuer-noun-378 = The server presented a certificate with an empty issuer distinguished name
legacy-extension-noun-376 = This is a legacy extension, be aware that these are no longer fully supported.
location-aware-browsing-noun-269 = Websites that use location-aware browsing will ask where you are in order to bring you more relevant information
mainstream-adjective-268 = Product exploration initiatives like our ‘connected devices’ program aim to bring more mainstream products
mass-surveillance-noun-267 = Calling on lawmakers all over the globe to rein in mass surveillance
meme-noun-266 = Keep making memes posting links and getting creative on the Web
milestone-noun-265 = Take a closer look at who we are including some of our biggest achievements and milestones
misinformation-noun-263 = We’re campaigning to get big tech platforms like Google, Facebook and Twitter to become more transparent about how political messages are spread so that we can detect and stop misinformation.
mobilize-verb-264 = This approach enables Mozilla to simultaneously build our capacity to mobilize millions of people quickly
native-adjective-262 = They can’t access the device’s underlying capabilities the way that native apps can
net-neutrality-noun-261 = A decentralized internet owned by all of us is where net neutrality interoperability competition and local contribution thrive
nonprofit-noun-259 = Mozilla is proudly nonprofit and answers to no one but you
non-profit-adjective-260 = Mozilla is proudly nonprofit and answers to no one but you
openness-noun-258 = Building with open standards and open source in our own products and supporting openness at every opportunity
open-source-adjective-375 = These terms are not intended to limit any rights granted under open source licenses
optimize-verb-257 = We optimize Firefox for the way you use the Web
override-verb-374 = Override the colors specified by the page with your selections
participation-noun-256 = Mozilla achieves success by helping more people make choices about what software they want to use what level of participation they would like to have online
pioneered-verb-255 = Mozilla is proud of the many technologies we have pioneered and submitted
pledge-noun-254 = The Mozilla community has pledged to protect and promote a platform providing opportunity
pop-up-noun-373 = You have blocked pop-ups for this website.
pre-alpha-adjective-253 = Are you a power-user comfortable installing pre-alpha software
preference-noun-250 = You can manage your profile and preferences
pre-installed-adjective-252 = This powerful extension that comes pre-installed with Firefox Developer Edition
pre-release-adjective-251 = Experience cutting-edge features in a pre-release browser
private-browsing-noun-249 = Private browsing in Firefox limits saving data about which sites and pages you have visited online
proactive-adjective-248 = They can be proactive about protecting users’ information
programmer-noun-247 = Mozilla programmers recommend these easy encryption tools
release-noun-372 = The security certificate in use on this website will no longer be trusted in a future release
remix-verb-246 = Learn how to remix content to create something new
report-noun-371 = Send a crash report for the tab you are viewing
report-verb-370 = Report errors like this to help Mozilla identify and block malicious sites
revert-verb-369 = Revert Bookmarks; Do you want to revert the changes you made to this scratchpad?
safeguard-noun-245 = When surveillance is too broad or lacks key safeguards
seamless-adjective-244 = Make sure you understand the tradeoffs of that seamless online experience
search-suggestion-noun-368 = Search suggestions will not be shown in location bar results
security-keys-noun-367 = %S wants to register an account with one of your security keys. You can connect and authorize one now, or cancel.
sensitive-adjective-366 = As a security precaution, the browser does not automatically re-request sensitive documents
sidebar-noun-364 = Load this bookmark in the sidebar
signer-noun-363 = The signer’s certificate could not be found
snoop-verb-243 = Anyone who chooses to snoop can see some or all of your activity
software-noun-242 = No software provides perfect protection from spying
spam-verb-240 = Like phishing eg a fake bank email asking for your personal information spamming hacked accounts
spam-noun-241 = Thunderbird’s popular junk mail tools have been updated to stay ahead of spam
sprint-noun-239 = MozCamps are regional events that bring together core paid and volunteer Mozilla staff members from all areas of the project for two full days of presentations discussions brainstorms work sprints hackathons and of course a little bit of fun
stakeholder-noun-238 = As with most issues of importance we believe education listening and dialogue amongst stakeholders are critical to finding solutions
stakeholder-noun-237 = Listening and dialogue amongst stakeholders are critical to finding solutions
student-ambassador-noun-236 = Join us as a student ambassador
studies-noun-365 = We are running a series of studies in Nightly. All Nightly users will receive a notification about these studies.  When a study is active, Nightly Firefox will automatically use Cloudflare’s 1.1.1.1 secure DNS over HTTPS.  The first study will use the Cloudflare resolver in addition to the DNS selected by a user or their ISP to compare approaches.
surf-verb-235 = So avoid sensitive activities when surfing in public
surveillance-noun-234 = The difference now is that they’ve moved beyond binoculars bugs and bad guys surveillance has gone digital
tabbed-adjective-233 = If you like Firefox’s tabbed browsing you’re going to love tabbed email
tech-noun-232 = Get the Mozilla newsletter for our latest tech news and more
technologist-noun-231 = We connect support and amplify the work of technologists
thinkers-noun-230 = Mozillians are a diverse group of thinkers builders educators and hackers
third-party-noun-229 = Mozilla sites are no exception Like most other Web sites we also use third party tools
third-party-adjective-228 = Mozilla sites are no exception Like most other Web sites we also use third party tools
tinker-verb-227 = Mozilla‘s vision of the Internet is a place where anyone can access information a place where everyone can hack and tinker
track-verb-360 = Block third-party content that tracks you around the web. Control how much of your online activity gets stored and shared between websites.
trackers-noun-361 = Blocking trackers and cookies can cause some websites to break.
trackers-noun-226 = Firefox protects your online privacy and blocks trackers
tracking-content-noun-359 = Websites may load external ads, videos, and other content that contain tracking code. Blocking tracking content can help sites load faster, but some buttons, forms, and login fields might not work.
trojan-horse-noun-225 = Antimalware features protect you from trojan horses and spyware
troubleshoot-verb-224 = Help easily identify and troubleshoot performance bottlenecks
turbo-mode-noun-357 = Enable Turbo Mode for faster browsing.
unencrypted-adjective-356 = Your email and authentication are sent unencrypted so your password and your message could easily be read by other people
universal-access-noun-223 = Digital inclusion means promoting diversity practicing respect and supporting universal access online
unleash-verb-222 = We launched Firefox OS to unleash the full power of the Web
unresponsive-adjective-355 = A script from the extension is running on this page, and making it unresponsive.
unsafe-adjective-354 = Disabling the Safe Browsing feature is not recommended as it may result in you going to unsafe sites
user-control-noun-221 = Firefox OS is the first truly open operating system for mobile devices delivering the same security privacy customization and user control
validate-verb-352 = Validate cache manifest
validity-noun-353 = Query OCSP responder servers to confirm the current validity of certificates
version-noun-351 = This policy is only available on the Extended Support Release (ESR) version
viable-adjective-220 = We’ve built the technologies and APIs to make the Web a rich and viable option
web-authentication--350 = Open Web Authentication panel
web-literacy-noun-218 = Participate in the web by testing your web literacy skills
web-literate-adjective-217 = Mozilla Webmaker works to create a more Web-literate plane
web-literate-adjective-216 = Mozilla Webmaker works to create a more Web-literate plane
webmakers-noun-215 = Mozilla is mobilized to ensure the protection of the Web and to empower tomorrow’s webmakers
webmaking-noun-214 = And if you ever want to talk about Webmaking and teaching I’m always available
