# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (relinkDenied.message): Ideally, this string is short (it's
# a toast message).
relinkDenied.message2 = Hai già effettuato l’accesso a Sync?
test2 = Test2
test3 = Test3
key = space = Uno spazio all'interno di una chiave
new = Novo
se\:dva = Se dva
se = ena = Bla dva
pre-translate = Tradotto prima dell’aggiunta della fonte
pre-translate-2 = Tradotto prima dell’aggiunta della fonte 2
pre-translate-3 = Tradotto prima dell’aggiunta della fonte 3
pre-translate-4 = Tradotto prima dell’aggiunta della fonte 4
pre-translate-5 = Tradotto prima dell’aggiunta della fonte 5
pre-translate-6 = Tradotto prima dell’aggiunta della fonte 6
pre-translate-7 = Tradotto prima dell’aggiunta della fonte 7
pre-translate-new = Stringa appena aggiunta
