# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# The following are used by the imap code to display progress/status/error messages

# LOCALIZATION NOTE(imapAlertDialogTile): Do not translate the word "%S"
# below. Place the word %S where the account name should appear.
# imapAlertDialogTitle=Alert for account %S

# Status - opening folder
imapStatusSelectingMailbox = Apertura cartella %S…
# Status - create folder
imapStatusCreatingMailbox = Creazione cartella…
# Status - deleting a folder
# LOCALIZATION NOTE (imapStatusDeletingMailbox): The "%S" below should not be translated.
# Instead, insert "%S" in your translation where you wish to display the name
# of the folder being deleted.
imapStatusDeletingMailbox = Eliminazione cartella %S…
# Status - renaming mailbox
# LOCALIZATION NOTE (imapStatusRenamingMailbox): The "%S" below should not be translated.
# Instead, insert "%S" in your translation where you wish to display the name
# of the folder being renamed.
imapStatusRenamingMailbox = Ridenominazione della cartella %S…
# Status - looking for mailboxes
imapStatusLookingForMailbox = Ricerca cartelle…
# Status - subscribing to mailbox
# LOCALIZATION NOTE (imapStatusSubscribeToMailbox): The "%S" below should not be translated.
# Instead, insert "%S" in your translation where you wish to display the name
# of the folder being subscribed to.
imapStatusSubscribeToMailbox = Sottoscrizione alla cartella %S…
# Status - unsubscribing from mailbox
# LOCALIZATION NOTE (imapStatusUnsubscribeMailbox): The "%S" below should not be translated.
# Instead, insert "%S" in your translation where you wish to display the name
# of the folder being unsubscribed from.
imapStatusUnsubscribeMailbox = Annullamento sottoscrizione alla cartella %S…
# Status - searching imap folder
imapStatusSearchMailbox = Ricerca cartella…
# Status - closing a folder
imapStatusCloseMailbox = Chiusura cartella…
# Status - compacting a folder
imapStatusExpungingMailbox = Compattazione cartella…
# Status - logging out
imapStatusLoggingOut = Disconnessione in corso…
# Status - checking server capabilities
imapStatusCheckCompat = Verifica funzionalità server di posta…
# Status - logging on
imapStatusSendingLogin = Invio dati di accesso…
# Status - auth logon
imapStatusSendingAuthLogin = Invio dati di accesso…
imapDownloadingMessage = Download del messaggio…
# LOCALIZATION NOTE (imapGettingACLForFolder): Do not translate the word "ACL" below.
imapGettingACLForFolder = Recupero ACL cartella…
imapGettingServerInfo = Recupero informazioni di configurazione del server…
imapGettingMailboxInfo = Recupero informazioni di configurazione della casella di posta…
imapEmptyMimePart = Questa parte del corpo verrà scaricata su richiesta.
# LOCALIZATION NOTE (imapReceivingMessageHeaders3): Do not translate the words "%1$S", "%2$S", and "%3$S" below.
# Place the word %1$S in your translation where the number of the header being downloaded should appear.
# Place the word %2$S in your translation where the total number of headers to be downloaded should appear.
# Place the word %3$S in your translation where the name of the folder being processed should appear.
# Note: The account name and separators (e.g. colon, space) are automatically added to the status message.
# Example: "Joe's Account: Downloading message header 100 of 1000 in Drafts…"
imapReceivingMessageHeaders3 = Download dell’intestazione del messaggio %1$S di %2$S in %3$S…
# LOCALIZATION NOTE (imapReceivingMessageFlags3): Do not translate the words "%1$S", "%2$S", and "%3$S" below.
# Place the word %1$S in your translation where the number of the flag being downloaded should appear.
# Place the word %2$S in your translation where the total number of flags to be downloaded should appear.
# Place the word %3$S in your translation where the name of the folder being processed should appear.
# Note: The account name and separators (e.g. colon, space) are automatically added to the status message.
# Example: "Jim's Account: Downloading message flag 100 of 1000 in INBOX…"
imapReceivingMessageFlags3 = Download del flag messaggio %1$S di %2$S in %3$S…
imapDeletingMessages = Eliminazione messaggi…
imapDeletingMessage = Eliminazione messaggio…
# LOCALIZATION NOTE (imapMovingMessages): Do not translate the word "%S" below.
# Place the word %S in your translation where the name of the folder should appear.
imapMovingMessages = Spostamento messaggi in %S…
# LOCALIZATION NOTE (imapMovingMessage): Do not translate the word "%S" below.
# Place the word %S in your translation where the name of the folder should appear.
imapMovingMessage = Spostamento del messaggio in %S…
# LOCALIZATION NOTE (imapCopyingMessages): Do not translate the word "%S" below.
# Place the word %S in your translation where the name of the folder should appear.
imapCopyingMessages = Copia messaggi in %S…
# LOCALIZATION NOTE (imapCopyingMessage): Do not translate the word "%S" below.
# Place the word %S in your translation where the name of the folder should appear.
imapCopyingMessage = Copia messaggio in %S…
# LOCALIZATION NOTE (imapFolderReceivingMessageOf3): Do not translate the words "%1$S", "%2$S", and "%3$S" below.
# Place the word %1$S in your translation where the number of the message being downloaded should appear.
# Place the word %2$S in your translation where the total number of messages to be downloaded should appear.
# Place the word %3$S in your translation where the name of the folder being processed should appear.
# Note: The account name and separators (e.g. colon, space) are automatically added to the status message.
# Example: "Juan's Account: Downloading message 100 of 1000 in Sent…"
imapFolderReceivingMessageOf3 = Download del messaggio %1$S di %2$S in %3$S…
# LOCALIZATION NOTE (imapDiscoveringMailbox): Do not translate the word "%S" below.
# Place the word %S in your translation where the name of the folder should appear.
imapDiscoveringMailbox = Cartella trovata: %S
# LOCALIZATION NOTE (imapEnterServerPasswordPrompt): Do not translate the words %1$S and %2$S below.
# Place the word %1$S in your translation where the username should appear.
# Place the word %2$S in your translation where the servername should appear.
imapEnterServerPasswordPrompt = Inserisci la password per %1$S su %2$S:
# LOCALIZATION NOTE (imapServerNotImap4): Do not translate the word "IMAP4" below.
imapServerNotImap4 = Il server di posta %S non è un server di posta IMAP4.
# This is intentionally left blank.
imapDone =
imapEnterPasswordPromptTitle = Password del server di posta richiesta
imapUnknownHostError = Impossibile connettersi al server %S.
imapConnectionRefusedError = Impossibile connettersi al server di posta %S; la connessione è stata rifiutata.
imapNetTimeoutError = Connessione al server %S scaduta.
# Status - no messages to download
imapNoNewMessages = Non ci sono nuovi messaggi sul server.
imapDefaultAccountName = Posta per %S
imapSpecialChar = Il carattere %c è riservato su questo server imap. Scegli un altro nome.\u0020
imapPersonalSharedFolderTypeName = Cartella personale
imapPublicFolderTypeName = Cartella pubblica
imapOtherUsersFolderTypeName = Cartella di un altro utente
imapPersonalFolderTypeDescription = Questa è una cartella di posta personale.  Non è condiviso.
imapPersonalSharedFolderTypeDescription = Questa è una cartella di posta personale.  È stato condiviso.
imapPublicFolderTypeDescription = Questa è una cartella pubblica.
imapOtherUsersFolderTypeDescription = Questa è una cartella di posta condivisa dall’utente “%S”.
imapAclFullRights = Pieno controllo
imapAclLookupRight = Cerca
imapAclReadRight = Lettura
imapAclSeenRight = Imposta stato letto/non letto
imapAclWriteRight = Scrittura
imapAclInsertRight = Inserisci (Copia in)
imapAclPostRight = Pubblica
imapAclCreateRight = Crea sottocartella
imapAclDeleteRight = Elimina messaggi
imapAclAdministerRight = Amministra cartella
imapServerDoesntSupportAcl = Questo server non supporta le cartelle condivise.
imapAclExpungeRight = Elimina
imapServerDisconnected = Il server %S è stato disconnesso. Il server potrebbe essere inattivo o potrebbe essersi verificato un problema di rete.
# LOCALIZATION NOTE (autoSubscribeText): %1$S is the imap folder.
imapSubscribePrompt = Iscriversi a %1$S?
imapServerDroppedConnection = Impossibile connettersi al server IMAP. È possibile che il numero massimo di connessioni a questo server sia stato superato. In tal caso, utilizzare la finestra di dialogo Impostazioni avanzate del server IMAP per ridurre il numero di connessioni memorizzate nella cache.
imapQuotaStatusFolderNotOpen = Le informazioni sulle quote non sono disponibili in quanto la cartella non è aperta.
imapQuotaStatusNotSupported = Questo server non supporta le quote.
imapQuotaStatusNoQuota = Non ci sono quote di archiviazione per questa cartella.
# Out of memory
imapOutOfMemory = L’applicazione ha esaurito la memoria.
# LOCALIZATION NOTE (imapCopyingMessageOf2): Do not translate the word "%S" below.
# Place the word %3$S in your translation where the name of the destination folder should appear.
# Place the word %1$S where the currently copying message should appear.
# Place the word %2$S where the total number of messages should appear.
imapCopyingMessageOf2 = Copia del messaggio %1$S di %2$S in %3$S…
# LOCALIZATION NOTE (imapMoveFolderToTrash): Do not translate the word %S below.
# "%S" is the the name of the folder.
imapMoveFolderToTrash = Eliminare la cartella “%S”?
# LOCALIZATION NOTE (imapDeleteNoTrash): Do not translate the word %S below.
# "%S" is the the name of the folder.
imapDeleteNoTrash = L’eliminazione di questa cartella non è annullabile e verranno eliminati tutti i messaggi in essa contenuti e le relative sottocartelle. Eliminare comunque la cartella “%S”?
imapDeleteFolderDialogTitle = Elimina cartella
imapDeleteFolderButtonLabel = &Elimina cartella
# LOCALIZATION NOTE (imapAuthChangeEncryptToPlainSSL): %S is the server hostname
imapAuthChangeEncryptToPlainSSL = Il server IMAP %S sembra non supportare le password crittate. Se hai appena impostato questo account, prova a impostare “Password normale” come “Metodo di autenticazione” in “Impostazioni account | Impostazioni server”. Se prima funzionava e ora improvvisamente si guasta, contatta il tuo amministratore o provider di posta elettronica.
# LOCALIZATION NOTE (imapAuthChangePlainToEncrypt): %S is the server hostname
imapAuthChangePlainToEncrypt = Il server IMAP %S non consente password in chiaro. Provare a impostare “Password crittata” come “Metodo di autenticazione” in “Impostazioni account | Impostazioni server”.
# LOCALIZATION NOTE (imapAuthChangeEncryptToPlainNoSSL): %S is the server hostname
imapAuthChangeEncryptToPlainNoSSL = Il server IMAP %S sembra non supportare le password crittate. Se hai appena impostato l’account, prova a impostare “Password, trasmissione non sicura” come “Metodo di autenticazione” in “Impostazioni account | Impostazioni server”. Se prima funzionava e ora improvvisamente non funziona, questo è uno scenario comune in cui qualcuno potrebbe rubare la tua password.
# LOCALIZATION NOTE (imapAuthMechNotSupported): %S is the server hostname
imapAuthMechNotSupported = Il server IMAP %S non supporta il metodo di autenticazione selezionato. Modificare il “Metodo di autenticazione” in “Impostazioni account | Impostazioni server”.
# LOCALIZATION NOTE (imapAuthGssapiFailed): %S is the server hostname
imapAuthGssapiFailed = Il ticket Kerberos/GSSAPI non è stato accettato dal server IMAP %S. Verificare di aver effettuato l’accesso all’area di autenticazione Kerberos/GSSAPI.
# LOCALIZATION NOTE (imapServerCommandFailed):
# Place the word %1$S in your translation where the name of the account name should appear.
# Place the word %2$S in your translation where the server response should appear.
imapServerCommandFailed = Il comando corrente non è riuscito. Il server di posta per l’account %1$S ha risposto: %2$S\u0020
# LOCALIZATION NOTE (imapFolderCommandFailed): Do not translate the word %S below.
# Place the word %1$S in your translation where the name of the account should appear.
# Place the word %2$S in your translation where the name of the folder should appear.
# Place the word %3$S in your translation where the server response should appear.
imapFolderCommandFailed = L’operazione corrente su “%2$S” non è riuscita. Il server di posta per l’account %1$S ha risposto: %3$S
# LOCALIZATION NOTE (imapServerAlert):
# Place the word %1$S in your translation where the name of the account should appear.
# Place the word %2$S in your translation where the alert from the server should appear.
imapServerAlert = Avviso dall’account %1$S: %2$S
